name: llm
channels:
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  # Base
  - conda-forge::python=3.10
  - pytorch::pytorch=>2.1
  - pytorch::pytorch-cuda=11.8
  - nvidia::cuda=11.8
  # Libraries
  - conda-forge::accelerate
  - conda-forge::einops
  - conda-forge::scipy
  - conda-forge::transformers