num_train_epochs: 1
evaluation_strategy: epoch
log_level: info
logging_steps: 1
max_grad_norm: 1.0
output_dir: hf
per_device_train_batch_size: 8
per_device_eval_batch_size: 8
report_to: wandb
run_name: my_first_hydra_run  #--------CHANGE ME! CHANGE ME! CHANGE ME!--------
hub_model_id: LLMsForHepth/my_first_run  #--------CHANGE ME! CHANGE ME! CHANGE ME!--------
hub_private_repo: true
push_to_hub: false