# Default configurations which control inference
defaults:
  - dataset: full         # Specifies the dataset to be used
  - inference: infer_hf   # Specifies the inference configuration
  - _self_                # Ensures defaults are resolved in this file context

# Hydra configurations
hydra:
  run:
    dir: hydra_outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}  # Output directory with timestamp formatting
  job:
    chdir: false  # Prevent changing the working directory
