defaults:
  - optimizer: adamw
  - dataset: full
  - model: model
  - tokenizer: tokenizer
  - training: training_args
  - callbacks: callbacks
  - _self_

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}-${training.run_name}
  job:
    chdir: true